### ISSUE TITLE
vue 3 tooltip component encounters null reference in combination with vue-router

### ISSUE THREAD

**Issue by paulholtom** [Akryum/floating-vue#817]
There's an issue where under very particular circumstances it seems like vue-router can cause the watch on the popper triggers prop to execute before the component has been mounted, which results in an error because the $_events array is null.

The issue can be reproduced in the attached application by running the vue-cli dev server (there's a serve script in the package.json to do this) then loading the page in a browser. The error occurs immediately.

The error occurs in both Chrome and Firefox.

[tooltip-issue.zip](https://github.com/Akryum/v-tooltip/files/7865509/tooltip-issue.zip)

**Comment by mateuswetah** [comment]
@Akryum, saw that a fix is coming up, just wondering if this would also be related to this error message that I'm getiing on the console every vue-router transition as well:

```
Uncaught TypeError: _vm.$refs.popperContent is undefined
    handleGlobalClose
    handleGlobalClick 
   ...
```
It doesn't seem to break anything, but its weird. My `floating-vue` version is `^1.0.0-beta.8` since I still need Vue `2.6.x`.

**Comment by Akryum** [comment]
@mateuswetah The fix has already been released. Please open a new issue as it looks like it's a different one.
